### PR TITLE
Update sanitize file

### PR DESCRIPTION
**Pull request by afinegan**

### CODE REVIEW

**Comment by Aterfax** [comment]
Happy to include this as another DockerMod for the image like DCS Retribution but it would need to be restructured a bit to work as an overlay on the filesystem in the manner the DockerMods require.

This was also a good reminder that I should have added warnings about those functions being enabled is a risk - see: https://forum.dcs.world/topic/298332-what-do-the-sanitizemondules-x-lua-commands-do/?do=findComment&comment=4943174

**Comment by afinegan** [comment]
I didn't mean to make it a PR into your project, this is the full DDCS 4.0
- one of the top multiplayer servers in the list, I am Drex.
I have a 5.0 in the works, but am done with windows, and I feel your
project can get me off windows for the server lol

The project was open source at one point, but people were just copying and
putting up servers identical to mine using the code, splitting my
community...

There's over 5+ years of development in that code (one of the first to
properly use Combat Arms.) - have a 9900+ dcs world discord discord for it

I did want to thank you for how quick you fixed it, I wish I knew wine
better - was going to ask how you figured out about the override that
would fix it

- Andrew "drex" finegan

**Comment by Aterfax** [comment]
Fair enough! This said, I wanted to highlight that as this project is currently GPL-3.0 licensed only (a fairly "infectious" license), you may need to take some care to ensure you don't inadvertently need to disclose your own DDCS 4.0 code to meet the licensing requirements.

My understanding is that essentially you must not bundle any of your DDCS 4.0 code into the docker containers you distribute or you would then be required to make all your source code available.

Recommend a reading of https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60. That said, I'm not a license expert and will probably cross license this soon to avoid complications with GPL as it's not my intention to stifle downstream usage of this docker / project.

**Comment by afinegan** [comment]
My project thats forked off of your is public:
https://github.com/afinegan/DCS-World-Dedicated-Server-Docker

I am probably going to get that stress test you wanted, 20 players on the server right now, 1112 units on the ground, and some are even moving atm. Ill keep you updated - do you have a discord, I can put that info in, I did send you a friend request (drex or d0cX on discord)

As for GPL exposing the docker images it connects to, I am not worried - I will use docker mod one of these days, and clean up the code I wrote (it was written too quick - no unit test, I know I know lol - not the signs of a 23 year staff developer - 5.0 is significantly cleaner)

image

**Pull request closed without merging**
